[[redirects]]
  from = "/chats/find-all?size=100"
  to = "http://15.165.207.71:8080/chats/find-all?size=100"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "http://15.165.207.71:8080/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200