[[redirects]]
  from = "members/*"
  to = "https://e76d-211-108-235-4.ngrok-free.app/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "chats/*"
  to = "https://e76d-211-108-235-4.ngrok-free.app/:splat"
  status = 200
  force = true